/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksiDB;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Nursy
 */
public class vLap_anggota extends javax.swing.JFrame {
private ResultSet RsKoprasi;
private DefaultTableModel tabmode; 
private String trans;
    /**
     * Creates new form vLap_anggota
     */
    public vLap_anggota() {
        initComponents();
        Combobox();
        
    }
    
    public void Combobox(){
        { //db.koneksiDatabase();
        try {
            String sql = "select * from  dt_divisi order by nama asc";
            //Statement st = db.getKoneksi().createStatement();
            RsKoprasi = koneksiDB.getRS(sql);
             
            while (RsKoprasi.next()) {                
                CB_department.addItem(RsKoprasi.getString("nama"));
            }
             
            RsKoprasi.last();
            int jumlahdata = RsKoprasi.getRow();
            RsKoprasi.first();
             
        } catch (SQLException e) {
        }
      }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        RB_seluruhAnggota = new javax.swing.JRadioButton();
        CB_department = new javax.swing.JComboBox<>();
        RB_anggotaByDepartment = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        btCetak = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("LAPORAN - DATA ANGGOTA");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 60));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 380, 7));

        RB_seluruhAnggota.setBackground(new java.awt.Color(0, 153, 0));
        bg.add(RB_seluruhAnggota);
        RB_seluruhAnggota.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        RB_seluruhAnggota.setText("SELURUH ANGGOTA KOPERASI");
        RB_seluruhAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB_seluruhAnggotaActionPerformed(evt);
            }
        });
        jPanel1.add(RB_seluruhAnggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 320, -1));

        CB_department.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Departement" }));
        jPanel1.add(CB_department, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 130, 23));

        RB_anggotaByDepartment.setBackground(new java.awt.Color(0, 153, 0));
        bg.add(RB_anggotaByDepartment);
        RB_anggotaByDepartment.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        RB_anggotaByDepartment.setText("ANGGOTA PER-DEPARTEMEN");
        RB_anggotaByDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB_anggotaByDepartmentActionPerformed(evt);
            }
        });
        jPanel1.add(RB_anggotaByDepartment, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 340, 10));

        btCetak.setBackground(new java.awt.Color(153, 255, 153));
        btCetak.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btCetak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/print.png"))); // NOI18N
        btCetak.setText("CETAK");
        btCetak.setAlignmentY(0.0F);
        btCetak.setBorder(null);
        btCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCetakActionPerformed(evt);
            }
        });
        jPanel1.add(btCetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 90, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void RB_seluruhAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB_seluruhAnggotaActionPerformed
        CB_department.setEnabled(false);
        CB_department.setSelectedItem("Pilih Departement");
    }//GEN-LAST:event_RB_seluruhAnggotaActionPerformed

    private void btCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCetakActionPerformed
        if(RB_seluruhAnggota.isSelected()) {
            try{
            //String Response = JOptionPane.showInputDialog(null, "Masukkan Bulan","Laporan Per-Bulan",JOptionPane.QUESTION_MESSAGE);
            //String Response1 = JOptionPane.showInputDialog(null, "Masukkan Tahun","Laporan Per-Bulan",JOptionPane.QUESTION_MESSAGE);
            String Logo = new File("src\\images\\logo fix.png").getAbsolutePath();
            String NamaFile = "./src/report/LaporanDataAnggota.jasper";
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection koneksi = DriverManager.getConnection("jdbc:mysql://localhost/kk_7utama","root","");
            HashMap param = new HashMap();
            //Mengambil parameter
            param.put("gambar",Logo);
           // param.put("bulan",Response);
            //param.put("tahun",Response1);

            JasperPrint JPrint = JasperFillManager.fillReport(NamaFile, param, koneksi);
            JasperViewer.viewReport(JPrint,false);
            JasperViewer.setDefaultLookAndFeelDecorated(true);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Data tidak dapat di cetak","cetak data",JOptionPane.ERROR_MESSAGE);
            
        }
        } else if(RB_anggotaByDepartment.isSelected()) {
            String combo = CB_department.getModel().getSelectedItem().toString();
                            try{
            String Logo = new File("src\\images\\logo fix.png").getAbsolutePath();
            String NamaFile = "./src/report/LaporanDataAnggota_1.jasper";
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection koneksi = DriverManager.getConnection("jdbc:mysql://localhost/kk_7utama","root","");
            HashMap param = new HashMap();
            //Mengambil parameter
            param.put("gambar",Logo);
            param.put("departement",combo);
            

            JasperPrint JPrint = JasperFillManager.fillReport(NamaFile, param, koneksi);
            JasperViewer.viewReport(JPrint,false);
            JasperViewer.setDefaultLookAndFeelDecorated(true);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Data tidak dapat di cetak","cetak data",JOptionPane.ERROR_MESSAGE);
            
        }
    
      }
    
    }//GEN-LAST:event_btCetakActionPerformed

    private void RB_anggotaByDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB_anggotaByDepartmentActionPerformed
        CB_department.setEnabled(true);
        CB_department.setSelectedItem("Pilih Departement");
        
    }//GEN-LAST:event_RB_anggotaByDepartmentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vLap_anggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vLap_anggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vLap_anggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vLap_anggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vLap_anggota().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CB_department;
    private javax.swing.JRadioButton RB_anggotaByDepartment;
    private javax.swing.JRadioButton RB_seluruhAnggota;
    private javax.swing.ButtonGroup bg;
    private javax.swing.JButton btCetak;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
