/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksiDB;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Nursy
 */
public class vLap_angsuran extends javax.swing.JFrame {
private ResultSet RsKoprasi;
private DefaultTableModel tabmode; 
private String trans;
    /**
     * Creates new form vLap_anggota
     */
    public vLap_angsuran() {
        initComponents();
        Combobox();
    }

    public void Combobox(){
        { //db.koneksiDatabase();
        try {
            String sql = "select * from  dt_anggota order by nama asc";
            //Statement st = db.getKoneksi().createStatement();
            RsKoprasi = koneksiDB.getRS(sql);
             
            while (RsKoprasi.next()) {                
                CB_anggota.addItem(RsKoprasi.getString("nama"));
            }
             
            RsKoprasi.last();
            int jumlahdata = RsKoprasi.getRow();
            RsKoprasi.first();
             
        } catch (SQLException e) {
        }
      }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        RB_angsuranPeriode = new javax.swing.JRadioButton();
        CB_anggota = new javax.swing.JComboBox<>();
        RB_angsuranAnggota = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        btCetak = new javax.swing.JButton();
        endDate = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        startDate = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("LAPORAN - DATA ANGSURAN");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 60));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 420, 7));

        RB_angsuranPeriode.setBackground(new java.awt.Color(0, 153, 0));
        bg.add(RB_angsuranPeriode);
        RB_angsuranPeriode.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        RB_angsuranPeriode.setText("ANGSURAN PER PERIODE");
        RB_angsuranPeriode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB_angsuranPeriodeActionPerformed(evt);
            }
        });
        jPanel1.add(RB_angsuranPeriode, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 360, -1));

        CB_anggota.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Nama" }));
        jPanel1.add(CB_anggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 150, 23));

        RB_angsuranAnggota.setBackground(new java.awt.Color(0, 153, 0));
        bg.add(RB_angsuranAnggota);
        RB_angsuranAnggota.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        RB_angsuranAnggota.setText("ANGSURAN PER-NAMA ANGGOTA");
        RB_angsuranAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB_angsuranAnggotaActionPerformed(evt);
            }
        });
        jPanel1.add(RB_angsuranAnggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 380, 10));

        btCetak.setBackground(new java.awt.Color(153, 255, 153));
        btCetak.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btCetak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/print.png"))); // NOI18N
        btCetak.setText("CETAK");
        btCetak.setAlignmentY(0.0F);
        btCetak.setBorder(null);
        btCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCetakActionPerformed(evt);
            }
        });
        jPanel1.add(btCetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 90, 30));
        jPanel1.add(endDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 150, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Periode Awal");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, 20));
        jPanel1.add(startDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 150, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Periode Akhir");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void RB_angsuranPeriodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB_angsuranPeriodeActionPerformed
        CB_anggota.setEnabled(false);
        startDate.setEnabled(true);
        endDate.setEnabled(true);
        CB_anggota.setSelectedItem("Pilih Departement");
    }//GEN-LAST:event_RB_angsuranPeriodeActionPerformed

    private void btCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCetakActionPerformed
        if(RB_angsuranPeriode.isSelected()) {
            try{
            SimpleDateFormat Format1 = new SimpleDateFormat("dd MMMMM yyyy");
                String TanggalAwal = Format1.format(startDate.getDate().getTime());
                String TanggalAkhir = Format1.format(endDate.getDate().getTime());
                String Logo = new File("src\\images\\logo fix.png").getAbsolutePath();
                String NamaFile = "./src/report/LaporanDataAngsuran.jasper";
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection koneksi = DriverManager.getConnection("jdbc:mysql://localhost/kk_7utama","root","");
            HashMap param = new HashMap();
            //Mengambil parameter
            param.put("gambar",Logo);
            param.put("bulan",TanggalAwal);
            param.put("tahun",TanggalAkhir);

            JasperPrint JPrint = JasperFillManager.fillReport(NamaFile, param, koneksi);
            JasperViewer.viewReport(JPrint,false);
            JasperViewer.setDefaultLookAndFeelDecorated(true);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Data tidak dapat di cetak","cetak data",JOptionPane.ERROR_MESSAGE);
            
        }
        } else if(RB_angsuranAnggota.isSelected()) {
            String combo = CB_anggota.getModel().getSelectedItem().toString();
                            try{
            String Logo = new File("src\\images\\logo fix.png").getAbsolutePath();                    
            String NamaFile = "./src/report/LaporanDataAngsuran_1.jasper";
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            Connection koneksi = DriverManager.getConnection("jdbc:mysql://localhost/kk_7utama","root","");
            HashMap param = new HashMap();
            //Mengambil parameter
            param.put("gambar",Logo);
            param.put("anggotanama",combo);
            

            JasperPrint JPrint = JasperFillManager.fillReport(NamaFile, param, koneksi);
            JasperViewer.viewReport(JPrint,false);
            JasperViewer.setDefaultLookAndFeelDecorated(true);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Data tidak dapat di cetak","cetak data",JOptionPane.ERROR_MESSAGE);
            
        }
    
      }
    }//GEN-LAST:event_btCetakActionPerformed

    private void RB_angsuranAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB_angsuranAnggotaActionPerformed
       
        CB_anggota.setEnabled(true);
        startDate.setEnabled(false);
        endDate.setEnabled(false);
        CB_anggota.setSelectedItem("Pilih Departement");
    }//GEN-LAST:event_RB_angsuranAnggotaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vLap_angsuran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vLap_angsuran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vLap_angsuran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vLap_angsuran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vLap_angsuran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CB_anggota;
    private javax.swing.JRadioButton RB_angsuranAnggota;
    private javax.swing.JRadioButton RB_angsuranPeriode;
    private javax.swing.ButtonGroup bg;
    private javax.swing.JButton btCetak;
    private com.toedter.calendar.JDateChooser endDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private com.toedter.calendar.JDateChooser startDate;
    // End of variables declaration//GEN-END:variables
}
